# Generated by Django 5.2 on 2025-05-07 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='promotion_channel',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.service'),
            preserve_default=False,
        ),
    ]
